server:
  port: 80
  servlet:
    context-path: ""
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.24:3306/jpa_test?useUnicode=true?characterEncoding=utf8
    username: root
    password: root
mybatis:
  type-aliases-package: com.domain
  mapper-locations: classpath:mapper/*Mapper.xml